# https://taskfile.dev

version: '3'

tasks:

  clean:
    desc: Delete build artifacts
    cmds: [rm -rf bin/*]

  build:
    desc: Build all the examples and put them in ./bin
    dir: examples
    cmds:
      - |
        for i in *; do
          echo $i
          go build -o ../bin/$i ./$i
        done
    silent: true

  test:
    desc: Run the tests
    cmds:
      - mkdir -p bin
      - gotestsum -- -coverprofile=bin/cover.out ./...

  # Show all linters, enabled and disabled:
  #   golangci-lint help linters
  #
  # Pass -E/--enable to enable linter and -D/--disable to disable:
  #   golangci-lint run --no-config --disable-all -E errcheck ./...
  lint:
    desc: Lint the code.
    cmds:
      - golangci-lint run ./...

  browser:
    desc: "Show code coverage in browser (usage: task test:<subtarget> browser)"
    cmds:
      - go tool cover -html=bin/cover.out
