# https://taskfile.dev

version: '3'

tasks:

  clean:
    desc: Delete build artifacts
    cmds: [rm -rf bin/*]

  build:examples:
    desc: Build all the examples
    cmds:
      - go build -o bin/arguments        ./examples/arguments/
      - go build -o bin/calculator       ./examples/calculator/
      - go build -o bin/config_file      ./examples/config_file/
      - go build -o bin/counted          ./examples/counted/
      - go build -o bin/fake-git         ./examples/fake-git/
      - go build -o bin/naval_fate       ./examples/naval_fate/
      - go build -o bin/odd_even         ./examples/odd_even/
      - go build -o bin/options          ./examples/options/
      - go build -o bin/options_shortcut ./examples/options_shortcut/
      - go build -o bin/quick            ./examples/quick/
      - go build -o bin/type_assert      ./examples/type_assert/

  test:
    desc: Run the tests
    cmds:
      - go test -count=1 -short -coverprofile=bin/coverage.out -json ./... | tparse -skip

  browser:
    desc: "Show code coverage in browser (usage: task test:<subtarget> browser)"
    cmds:
      - go tool cover -html=bin/coverage.out